apiVersion: apps/v1
kind: Deployment
metadata:
  name: Return
  labels:
    app: Return
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Return
  template:
    metadata:
      labels:
        app: Return
    spec:
      containers:
        - name: Return
          image: username/Return:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5